---
apiVersion: v1
kind: Namespace
metadata:
  name: webdav
  labels:
    name: lab

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-webdav
  name: deployment-webdav
  namespace: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-webdav
  template:
    metadata:
      labels:
        app: deployment-webdav
    spec:
      containers:
      - env:
        - name: AUTH_TYPE
          value: Digest
        - name: USERNAME
          value: stanislas
        - name: PASSWORD
          value: secret12345
        - name: LOCATION
          value: '/webdav'
        image: bytemark/webdav
        imagePullPolicy: Always
        name: webdav-server
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: svc-webdav
  labels:
    app: svc-webdav
  namespace: webdav
spec:
  ports:
  - name: webdav-port-1
    port: 8080
    nodePort: 30080
    protocol: TCP
    targetPort: 80
  selector:
      app: deployment-webdav
  type: NodePort
